apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: cloudcode-kubernates
build:
  artifacts:
  - image: skaffold-spring-boot-example
    context: .
    jib: {}
deploy:
  kubectl:
    manifests:
    - k8s-deployment.yml
    - k8s-service.yml
